services:
  plurk-viewer:
    image: plurk-backup-viewer
    platform: linux/amd64
    build: .
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8001:8001"
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    volumes:
      - ./viewer/:/app/viewer/:ro
      - ./data/:/app/data/
